# Generated by Django 5.2.7 on 2026-03-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_identityprofile_entity_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='identifier_code',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
