# Generated by Django 5.2.7 on 2026-03-23 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_entity_identifier_code_entity_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='identityprofile',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='identityprofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
